class haxey_MIL_TAL
{
	name = "h. Milice - Taliban";
	class Infantry
	{
		name = "Groupes";
		GROUP2(haxey_MIL_TAL_GRP1,HQ Team,haxey_faction_Milice_Taliban,2,haxey_Milice_Taliban_Infantry_PL,CAPTAIN,haxey_Milice_Taliban_Infantry_PL,CAPTAIN)
		GROUP3(haxey_MIL_TAL_GRP2,DShKM Team,haxey_faction_Milice_Taliban,2,haxey_Milice_Taliban_Infantry_TL,CORPORAL,haxey_Milice_Taliban_Infantry_DShKM,PRIVATE,haxey_Milice_Taliban_Infantry_ADShKM,PRIVATE)
		GROUP7(haxey_MIL_TAL_GRP3,Group PKM,haxey_faction_Milice_Taliban,2,haxey_Milice_Taliban_Infantry_SL,SERGEANT,haxey_Milice_Taliban_Infantry_TL,CORPORAL,haxey_Milice_Taliban_Infantry_HG,PRIVATE,haxey_Milice_Taliban_Infantry_AHG,PRIVATE,haxey_Milice_Taliban_Infantry_rflm_1,PRIVATE,haxey_Milice_Taliban_Infantry_HG,PRIVATE,haxey_Milice_Taliban_Infantry_rflm_3,PRIVATE)
		GROUP7(haxey_MIL_TAL_GRP4,Group Marksman,haxey_faction_Milice_Taliban,2,haxey_Milice_Taliban_Infantry_SL,SERGEANT,haxey_Milice_Taliban_Infantry_TL,CORPORAL,haxey_Milice_Taliban_Infantry_M,PRIVATE,haxey_Milice_Taliban_Infantry_rflm_1,PRIVATE,haxey_Milice_Taliban_Infantry_rflm_2,PRIVATE,haxey_Milice_Taliban_Infantry_rflm_3,PRIVATE,haxey_Milice_Taliban_Infantry_AR,PRIVATE)
		GROUP7(haxey_MIL_TAL_GRP5,Group Martyr,haxey_faction_Milice_Taliban,2,haxey_Milice_Taliban_Infantry_SL,SERGEANT,haxey_Milice_Taliban_Infantry_TL,CORPORAL,haxey_Milice_Taliban_Infantry_exp,PRIVATE,haxey_Milice_Taliban_Infantry_AR,PRIVATE,haxey_Milice_Taliban_Infantry_rflm_2,PRIVATE,haxey_Milice_Taliban_Infantry_rflm_3,PRIVATE,haxey_Milice_Taliban_Infantry_rflm_4,PRIVATE)
		GROUP7(haxey_MIL_TAL_GRP6,Group RPG,haxey_faction_Milice_Taliban,2,haxey_Milice_Taliban_Infantry_SL,SERGEANT,haxey_Milice_Taliban_Infantry_TL,CORPORAL,haxey_Milice_Taliban_Infantry_AT,PRIVATE,haxey_Milice_Taliban_Infantry_rflm_1,PRIVATE,haxey_Milice_Taliban_Infantry_rflm_2,PRIVATE,haxey_Milice_Taliban_Infantry_rflm_3,PRIVATE,haxey_Milice_Taliban_Infantry_rflm_4,PRIVATE)
		GROUP7(haxey_MIL_TAL_GRP7,Group Mixed,haxey_faction_Milice_Taliban,2,haxey_Milice_Taliban_Infantry_SL,SERGEANT,haxey_Milice_Taliban_Infantry_TL,CORPORAL,haxey_Milice_Taliban_Infantry_LAT,PRIVATE,haxey_Milice_Taliban_Infantry_AR,PRIVATE,haxey_Milice_Taliban_Infantry_rflm_2,PRIVATE,haxey_Milice_Taliban_Infantry_rflm_1,PRIVATE,haxey_Milice_Taliban_Infantry_rflm_4,PRIVATE)
	};
};
